name: ArXiv Paper Collector

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at 12 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-papers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pulls the latest code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Install all dependencies from requirements.txt

      - name: Run ArXiv Paper Extractor
        run: python scripts/fetch_papers.py  # Run the updated Python script
        
      - name: Get Current Year and Week Range
        run: |
          echo "YEAR=$(date +'%Y')" >> $GITHUB_ENV
          START_DATE=$(date -d 'last monday' +'%B%d')
          END_DATE=$(date -d 'last sunday' +'%B%d')
          FILE_NAME="${START_DATE}_to_${END_DATE}.md"
          echo "WEEKLY_FILE_NAME=$FILE_NAME" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add research_updates/${{ env.YEAR }}_papers/${{ env.WEEKLY_FILE_NAME }} || true
          git commit -m "📄 Weekly ArXiv paper update [${{ env.WEEKLY_FILE_NAME }}]" || echo "No changes to commit"
          git push || echo "No changes to push"
